# Generated by Django 5.2.10 on 2026-01-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0005_remove_order_notes_order_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Позвонили'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доставили'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Необработанный'), ('assembly', 'Сборка'), ('delivery', 'Доставка'), ('completed', 'Выполнено')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
