# Generated by Django 5.2.10 on 2026-02-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
