# Generated by Django 5.2.10 on 2026-01-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0003_remove_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Необработанный'), ('assembly', 'Сборка'), ('delivery ', 'Доставка'), ('completed', 'Выполнено')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
