# Generated by Django 5.2.10 on 2026-01-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], db_index=True, default='cash', max_length=20, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
