# Generated by Django 5.2.10 on 2026-01-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0007_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Необработанный'), ('assembly', 'Готовится'), ('delivery', 'Доставка'), ('completed', 'Выполнено')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
